### ISSUE TITLE
Windows 7-64 / Firefox Quantum 59.0.2 bug

### ISSUE THREAD

**Issue by Magicengr** [KishanBagaria/OCLB#2]
Hi Kishan - 

I've been using your wonderful One-Click Llama for some time now and now it doesn't seem to work at all with Tampermonkey on the PC I have that's running Windows 7 64-bit, but the latest Firefox. Is there something I can try to see what's going on?

Sincerely,
Peter

**Comment by KishanBagaria** [comment]
Hi Peter

I just tried it with Firefox 59 and it works here. Can you tell me what happens when you click the button or does the button not appear at all?

**Comment by Magicengr** [comment]
I looked at the code and it looks like there's a problem at the very beginning. See attached screenshot.

**Comment by KishanBagaria** [comment]
The attachment isn't here. You'll have to upload the image on GitHub.com

**Comment by Magicengr** [comment]
![2018-05-12 11_38_14-one click llama button](https://user-images.githubusercontent.com/38668365/40323039-d5c712e2-5cf9-11e8-91e1-e681d1283ad2.png)

**Comment by KishanBagaria** [comment]
Those should be normal. Can you send a screenshot of the main Tampermonkey settings page?

**Comment by Magicengr** [comment]
![2018-05-28 12_05_14-greenshot](https://user-images.githubusercontent.com/38668365/40623978-89f27f34-626f-11e8-9906-07c9be1a0cf0.png)

**Comment by KishanBagaria** [comment]
1. Click Config mode -> Advanced.
2. Scroll down and click Factory Reset

Let me know if it works.

**Comment by Magicengr** [comment]
Yay, happy spinning llamas again! Thank you so much!
