### ISSUE TITLE
Excessive buttons on @badges page

### ISSUE THREAD

**Issue by DRSDavidSoft** [KishanBagaria/OCLB#4]
<img width="525" alt="badges-oclb" src="https://user-images.githubusercontent.com/4673812/50742433-57096e00-1220-11e9-94c6-a9596c98ab17.png">

Since the profile urls have been changed, OCLB displays these buttons on the _overhead_ buttons of the <a href="https://www.deviantart.com/badges">@Badges</a> account.

https://github.com/KishanBagaria/OCLB/blob/3a195c2c045edab818ef0bcf4f3497aa94f8e834/OCLB.user.js#L452-L453

Very low priority, but something I thought was worth mentioning.

**Comment by KishanBagaria** [comment]
It's because of https://github.com/KishanBagaria/OCLB/blob/3a195c2c045edab818ef0bcf4f3497aa94f8e834/OCLB.user.js#L440

I added them for dAhub initially but I'm not sure if anyone else uses them. It should be safe to remove them in the next release.

**Comment by DRSDavidSoft** [comment]
Interesting, where did dAhub users used them?

**Comment by KishanBagaria** [comment]
The dAhub bot used it for comments it made on the GALGAL group. It was also used on a widget on https://dahub.deviantart.com

**Comment by DRSDavidSoft** [comment]
I see; though I always thought you were filtering for `/badges/llama`, instead.

BTW I'm also returning a link to user badges on [GALGAL](https://www.deviantart.com/giveallamagetallama) using dADroid,
so maybe you'd want to keep this for other bots instead of removing it?

In that case, you should rewrite the CSS selector to match the new address, e.g.:
```
a[href*=".deviantart.com/"][href*="/badges/"]
```

**Comment by KishanBagaria** [comment]
I suggested using `/badges/llama` to dAhub but he didn't end up using it. Instead it was always `/badges/:id`

Right, I'll keep it then.

**Comment by KishanBagaria** [comment]
https://github.com/KishanBagaria/OCLB/commit/d23e4e49339d27f515b4b1a3776b06e9436ca445
